import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/libs/auth-libs";
import "../style/globals.css";
import "../style/globals.scss";
import Bootstrap from '@/app/components/global/Bootstrap'
import Providers from "@/utils/provider";
// import UserInfo from "./components/dashboard/UserInfo";
// import Authpage from "./authpage/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({children}:Props) {
  return (
    <html lang="en">
        <Bootstrap/>
        <AuthProvider>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Providers>{children}</Providers>
          </body>
        </AuthProvider>
    </html>
  );
}
